apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-{{ IMGVERSION }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet
        version: v{{ IMGVERSION }}
    spec:
      containers:
      - name: dotnet
        image: hmdemo/dotnetcorebmb:{{ IMGVERSION }}
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8080