apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: dotnet-default
spec:
  destination:
    name: dotnet
  route:
  - labels:
      version: vCURRVERSION
    weight: 90
  - labels:
      version: vNEWVERSION
    weight: 10