apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-green
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: dotnet-bg
  template:
    metadata:
      labels:
        app: dotnet-bg
        color: green
    spec:
      containers:
        - name: front-end
          image: hmdemo/dotnetcorebmb:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20